Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"

    config.vm.synced_folder "./scripts", "/mnt/scripts"

    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        sh /mnt/scripts/develop.sh
        sh /mnt/scripts/virtualization.sh
    SHELL

end
